#!/bin/bash

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config                         \
    layout                bsp           \
    window_placement      second_child  \
    config top_padding    35            \
    top_padding           35            \
    bottom_padding        20            \
    left_padding          20            \
    right_padding         20            \
    window_gap            20            \
    window_border         on            \
    window_border_width   3             \
    mouse_modifier        alt           \
    window_opacity        off           \
    external_bar          all:32:0      \

yabai -m config mouse_modifier ctrl
# Left Click + Drag
yabai -m config mouse_action1 move 
# Right Click + Drag
yabai -m config mouse_action2 resize 

yabai -m mouse_drop_action swap

# Disable Specific Apps
APPS=(
  "^System Settings$"
  "^Calculator$"
  "^Finder$"
  "^Reminder$"
  "^Contact$"
  "^KakaoTalk$"
  "^Stickies$"
  "^Messages$"
  "^Steam Helper$"
  "^Digital Colour Meter$"
  "^Stats$"
  "^Installer$"
)
for app in "${APPS[@]}"; do
    yabai -m rule --add app="$app" manage=off
done

yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"
