#!/opt/homebrew/bin/lua

package.cpath = package.cpath .. ";/Users/" .. os.getenv("USER") .. "/.local/share/sketchybar_lua/?.so"

sbar = require("sketchybar")

sbar.begin_config()
sbar.hotload(true)
require("init")
sbar.end_config()

sbar.event_loop()
